### ISSUE TITLE
Error in rule find_16S

### ISSUE THREAD

**Issue by spleonard1** [metagenome-atlas/atlas#249]
another numpy error, this time during find_16S rule:

Traceback (most recent call last):
  File "/stor/work/Ochman/sean/projects/bee_metagenomes/databases/conda_envs/5f091142/bin/checkm", line 36, in <module>
    from checkm import main
  File "/stor/work/Ochman/sean/projects/bee_metagenomes/databases/conda_envs/5f091142/lib/python2.7/site-packages/checkm/main.py", line 23, in <module>
    Traceback (most recent call last):
import numpy as np
  File "/stor/work/Ochman/sean/projects/bee_metagenomes/databases/conda_envs/5f091142/bin/checkm", line 36, in <module>
  File "/usr/lib/python2.7/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
      File "/usr/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
from checkm import main
    from numpy.lib import add_newdoc
  File "/stor/work/Ochman/sean/projects/bee_metagenomes/databases/conda_envs/5f091142/lib/python2.7/site-packages/checkm/main.py", line 23, in <module>
  File "/usr/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python2.7/dist-packages/numpy/core/__init__.py", line 26, in <module>
    import numpy as np
  File "/usr/lib/python2.7/dist-packages/numpy/__init__.py", line 142, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: cannot import name multiarray

Error in rule find_16S:
    output: SRR7287198/binning/DASTool/SSU/ssu_summary.tsv, SRR7287198/binning/DASTool/SSU/ssu.fna
    shell:
        
        rm -r SRR7287232/binning/DASTool/SSU &&            checkm ssu_finder                --extension fasta                --threads 1                --evalue 1e-05                --concatenate 200                SRR7287232/SRR7287232_contigs.fasta                SRR7287232/binning/DASTool/bins                SRR7287232/binning/DASTool/SSU
        
        (exited with non-zero exit code)

Running atlas 2.2.0 on a linux machine. Let me know any other info I can provide. 

[2019-10-13T113906.088877.snakemake.log](https://github.com/metagenome-atlas/atlas/files/3722017/2019-10-13T113906.088877.snakemake.log)

Thanks for your help!

**Comment by SilasK** [comment]
The #250 should fix this. 
You can test it now by changing to the `updatecheckm` branch. 
Otherwise, you can de-select the annotation of 16S genes in the config file.

**Comment by spleonard1** [comment]
Thanks so much for your quick response! Sadly running atlas from the updatecheckm branch still throws some errors. Looks like it downloaded a new conda environment but the 16S rule
 fails with the following errors:
```ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: cannot import name multiarray

Traceback (most recent call last):
  File "/stor/work/Ochman/sean/projects/bee_metagenomes/databases/conda_envs/27b2deba/bin/checkm", line 36, in <module>
    from checkm import main
  File "/stor/work/Ochman/sean/projects/bee_metagenomes/databases/conda_envs/27b2deba/lib/python2.7/site-packages/checkm/main.py", line 23, in <module>
    import numpy as np
  File "/usr/lib/python2.7/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python2.7/dist-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: cannot import name multiarray```

Attached the log file. 
[2019-10-14T112245.248700.snakemake.log](https://github.com/metagenome-atlas/atlas/files/3725549/2019-10-14T112245.248700.snakemake.log)
How would I update the config.yaml to exclude these rules? Comment out the taxonomy lines?

**Comment by SilasK** [comment]
Comment out the line for ssu:
```
annotations:
  - gtdb_tree
  - gtdb_taxonomy
  - checkm_taxonomy
#  - ssu
```

**Comment by SilasK** [comment]
thank you for sending all the log files, I'll have a look at this.

**Comment by spleonard1** [comment]
Ok, thanks! I commented out -ssu and still got errors, this time in the "run_dal_tool" rule. Not sure if this is still the same issue somehow or if I should open a new one. Still on the updatecheckm branch. 
```
Error in rule run_das_tool:
    jobid: 168
    output: SRR7986809/binning/DASTool/SRR7986809_DASTool_summary.txt, SRR7986809/binning/DASTool/SRR7986809_DASTool_hqBins.pdf, SRR7986809/binning/DASTool/SRR7986809_DASTool_scores.pdf, SRR7986809/binning/DASTool/SRR7986809_metabat.eval, SRR7986809/binning/DASTool/SRR7986809_maxbin.eval, SRR7986809/binning/DASTool/cluster_attribution.tsv
    log: SRR7986809/logs/binning/DASTool.log (check log file(s) for error message)
    conda-env: /stor/work/Ochman/sean/projects/bee_metagenomes/databases/conda_envs/2c49a784
    shell:
         DAS_Tool --outputbasename SRR7986809/binning/DASTool/SRR7986809  --bins SRR7986809/binning/DASTool/metabat.scaffolds2bin,SRR7986809/binning/DASTool/maxbin.scaffolds2bin  --labels metabat,maxbin  --contigs SRR7986809/SRR7986809_contigs.fasta  --search_engine diamond  --proteins SRR7986809/annotation/predicted_genes/SRR7986809.faa  --write_bin_evals 1  --create_plots 1 --write_bin_evals 1  --megabin_penalty 0.5 --duplicate_penalty 0.6  --threads 8  --debug  --score_threshold 0.5 &> >(tee SRR7986809/logs/binning/DASTool.log)  ; mv SRR7986809/binning/DASTool/SRR7986809_DASTool_scaffolds2bin.txt SRR7986809/binning/DASTool/cluster_attribution.tsv &> >(tee -a SRR7986809/logs/binning/DASTool.log)
        (exited with non-zero exit code)

```
I've attached the new log and my config.yaml, in case I messed something else up in there.

[2019-10-14T173123.904176.snakemake.log](https://github.com/metagenome-atlas/atlas/files/3726644/2019-10-14T173123.904176.snakemake.log)

[config.yaml.txt](https://github.com/metagenome-atlas/atlas/files/3726645/config.yaml.txt)

**Comment by SilasK** [comment]
@spleonard1 I solved the problem for me with #250 .

If you want to test it out. run atlas with `-R initialize_checkm`


Could I ask you to send me your version of conda `conda --version``
And the version of *numpy* and *python* used in the checkm environment:

```
conda activate /stor/work/Ochman/sean/projects/bee_metagenomes/databases/conda_envs/27b2deba
conda list
```

**Comment by SilasK** [comment]
Could you send me the `SRR7986809/logs/binning/DASTool.log` log file please.

**Comment by spleonard1** [comment]
atlas run all -R initialize_checkm gave the same numpy multiarray errors, sadly. 

My info: 
conda 4.7.12


[conda.env.27b2deba.list.txt](https://github.com/metagenome-atlas/atlas/files/3730210/conda.env.27b2deba.list.txt)
[DASTool.log](https://github.com/metagenome-atlas/atlas/files/3730213/DASTool.log)

**Comment by SilasK** [comment]
This is another error.
From the log file:
> No bins with bin-score >0.5 found. Adjust score_threshold to report bins with lower quality.

It seems you don’t have good quality bins. Is this a surprise to you?


Check the sample/binning/maxbin folder. There is a summary file reporting sort of a completeness score (similar but not as good as checkM).

**Comment by spleonard1** [comment]
Not too surprising, some of the samples have pretty shallow coverage. I'll look at relaxing the score_threshold. Thanks! 

I figure low quality bins shouldn't break the pipeline, though- want me to open a new issue for that?
