### ISSUE TITLE
spades NOT using assembly_threads

### ISSUE THREAD

**Issue by AlexanderBartholomaeus** [metagenome-atlas/atlas#319]
How can I use spades with more than 1 thread. I set `assembly_threads: 16` but the spades does only use one core. 

Edit:
The same for megahit, also only 1 thread is used.

Where do I need to configure it?

**Comment by SilasK** [comment]
The `asembly_threads` from the config file should be passed correctly to spades/megahit. See the [code](https://github.com/metagenome-atlas/atlas/blob/a744644956ab143b1a0005f6c6022a0e027fcf8c/atlas/rules/assemble.snakefile#L393)
 
I don't understand why this is not the case. 

Can you try to run atlas with the command line arguments `-np` (dry-run and print shell commands) This shows you if these command lines are passed correctly to the spades command. 

Where do you know that spades is using only one thread? 
Do you allow for enough assembly_memory? 
What is your atlas version?

**Comment by AlexanderBartholomaeus** [comment]
Thank you for the fast answer!

I am using version 2.4.1 (installed ~3 weeks ago).

Output of the dry run attached, there it is also visable that only 1 thread is used. I saw the same before in the assembly log file of spades and also via htop system command.

I full sequence of my commands:
```
# init
atlas init --threads 16 --db-dir /opt/databases/atlas/ /ARCHIV/raw_files
# manual modification of the config.yaml -->assembly_threads: 16
# run all
atlas run all
```

I also init again, without manual change of assembly_threads and it is still the same.
[dry_out.txt](https://github.com/metagenome-atlas/atlas/files/5304513/dry_out.txt)

**Comment by SilasK** [comment]
Sorry, @AlexanderBartholomaeus thsi shouldn't happen. 

The underlying snakemake doesn't take into account the threads definition. I try to investigate further. 

Could you confirm that you have snakemake v 5.9 installed via

`conda list snakemake``
And maybe the python version you are using. 

As a solution you can modify the code on your computer in the file 

[`atlas/rules/assemble.snakefile`](https://github.com/metagenome-atlas/atlas/blob/a744644956ab143b1a0005f6c6022a0e027fcf8c/atlas/rules/assemble.snakefile#L393)

modify the config['assembly_threads'] to the number you want. 




Note for me: I just copied the important part of the log here.

```
[Wed Sep 30 11:29:22 2020]
rule run_spades:
    input: NG-25716-sub500k/assembly/reads/QC.errorcorr.merged_R1.fastq.gz, NG-25716-sub500k/assembly/reads/QC.errorcorr.merged_R2.fastq.gz, NG-25716-sub500k/assembly/reads/QC.errorcorr.merged_se.fastq.gz, NG-25716-sub500k/assembly/reads/QC.errorcorr.merged_me.fastq.gz
    output: NG-25716-sub500k/assembly/contigs.fasta, NG-25716-sub500k/assembly/scaffolds.fasta
    log: NG-25716-sub500k/logs/assembly/spades.log
    jobid: 83
    benchmark: logs/benchmarks/assembly/spades/NG-25716-sub500k.txt
    wildcards: sample=NG-25716-sub500k
    resources: mem=250, time=48

spades.py  --threads 1  --memory 250  -o NG-25716-sub500k/assembly  -k auto --meta     --pe1-1 NG-25716-sub500k/assembly/reads/QC.errorcorr.merged_R1.fastq.gz --pe1-2 NG-25716-sub500k/assembly/reads/QC.errorcorr.merged_R2.fastq.gz --pe1-s NG-25716-sub500k/assembly/reads/QC.errorcorr.merged_se.fastq.gz --pe1-m NG-25716-sub500k/assembly/reads/QC.errorcorr.merged_me.fastq.gz     --only-assembler  > NG-25716-sub500k/logs/assembly/spades.log 2>&1 

```

**Comment by SilasK** [comment]
If you are modifying the code. could you also just add a print(config['assembly_threads']) to see where the problem lies?

**Comment by AlexanderBartholomaeus** [comment]
I am using:
python 3.6.11 
snakemake 5.8.2

I tried to upgrade snakemake but there is no newer version. Maybe not for python 3.6. 

Where can I find the atlas/rules ?

**Comment by AlexanderBartholomaeus** [comment]
Or should I try a fresh installation with miniconda3 and python 3.7 or 3.8?

**Comment by SilasK** [comment]
I also use python 3.6 

- Ok. try to update snakemake to v 5.9  `conda update snakemake=5.9`

- Test again with the arguments `-np` and check if the correct threads are passed to spades (e.g. the part of the log I put above)

If it doesn't work:

Find out where atlas is installed. `which atlas`
something like `/miniconda3/pkgs/metagenome-atlas` or `/Users/username/anaconda/lib/python3.6/site-packages/metagenome-atlas`

Search for the file `atlas/rules/assemble.snakefile`

add at the beginning of the file the `print(config['assembly_threads'])`

And write the assembly_threads as a number in [Line 393](https://github.com/metagenome-atlas/atlas/blob/a744644956ab143b1a0005f6c6022a0e027fcf8c/atlas/rules/assemble.snakefile#L393)

**Comment by SilasK** [comment]
Can you send me your spades log, please?

**Comment by AlexanderBartholomaeus** [comment]
`print(config['assembly_threads'])` prints the expected threads. However, I figured out that non of the tools is using more than one core. Since I wanted to get some results I hardcoded the threads in the script as you suggested for assembly and error corrections steps because this is most time consuming. 

During the next days I will try a new fresh install including snakemake 5.9 and check again.

**Comment by SilasK** [comment]
I recently tested atlas with a fresh install in a docker container and did’t had the problem.

I’m looking forward to what your results are.

**Comment by AlexanderBartholomaeus** [comment]
Finally I found to time to test and fix the issue:

I finially downloaded miniconda3 again and installed a fresh version with the command provided at https://metagenome-atlas.readthedocs.io/en/latest/usage/getting_started.html# `mamba create -y -n atlasenv metagenome-atlas`. Is there is difference to the conda install `conda install -y -c bioconda -c conda-forge metagenome-atlas` ? After the fresh installation snakemake was again at v 5.8. `conda update snakemake=5.9` did not work I had to install `conda install snakemake=5.9` . Now everything seems to work, I still have the feeling that not all jobs work with more threads but after using `atlas run --job 516 all` it seem better. However, for the assembly the given threads are now used.

**Comment by slambrechts** [comment]
I'm experiencing the same problem. Installing snakemake 5.9 still the recommended way to fix this?

**Comment by SilasK** [comment]
I don't understand the error and I'm not sure why using snakemake 5.9 should solve the issue. 


 @slambrechts 
When you start atlas it gives the full snakemake command used. Is there the -j/--jobs/--cores argument defined or is it defined somewhere in your profile. 
Can you try by specifying the number or max threads you want. e.g. `-j 8`. 

Then you can use mamba to install another version of snakemake / atlas.

**Comment by slambrechts** [comment]
@SilasK The problem still exists when using atlas V 2.6a2, still only one thread is being used. Snakemake says:

```
[2021-05-25 22:19 INFO] Executing: snakemake --snakefile /scratch/gent/vo/000/gvo00043/vsc42339/conda/envs/atlas/lib/python3.7/site-packages/atlas/Snakefile --directory /kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/CLEAN_READS/test  --rerun-incomplete --configfile '/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/CLEAN_READS/test/config.yaml' --nolock   --use-conda --conda-prefix /kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs   --scheduler greedy  assembly  --resources mem=250 --cores 48 
localrules directive specifies rules that are not present in the Snakefile:
	verify_eggNOG_files
```

While in the spades log I find:

```
Command line: /kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/cbf79a0d/bin/spades.py	--threads	1	--memory	248	-o	/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/CLEAN_READS/test/DV-OTC13-B/assembly	-k	auto	--meta	--pe1-1	/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/CLEAN_READS/test/DV-OTC13-B/assembly/reads/QC.errorcorr.merged_R1.fastq.gz	--pe1-2	/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/CLEAN_READS/test/DV-OTC13-B/assembly/reads/QC.errorcorr.merged_R2.fastq.gz	--pe1-s	/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/CLEAN_READS/test/DV-OTC13-B/assembly/reads/QC.errorcorr.merged_se.fastq.gz	--pe1-m	/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/CLEAN_READS/test/DV-OTC13-B/assembly/reads/QC.errorcorr.merged_me.fastq.gz	--only-assembler
```


and `conda list snakemake` gives me 

```
# packages in environment at /scratch/gent/vo/000/gvo00043/vsc42339/conda/envs/atlas:
#
# Name                    Version                   Build  Channel
snakemake                 6.4.0                hdfd78af_0    bioconda
snakemake-minimal         6.4.0              pyhdfd78af_0    bioconda
```

**Comment by SilasK** [comment]
Do other rules run with more threads? 



In may case I get the 8 threads I put in. Snakemake reduces the number of threads if it detects that there are less threads on your machine. Could you send me the full snakemake log which can be found in `working dir/.snakemake/log`
