### ISSUE TITLE
Error in rule combine_contig_stats

### ISSUE THREAD

**Issue by farhadm1990** [metagenome-atlas/atlas#565]
Hello again, 

I am running `atlas run all --profile cluster --jobs 99` and I got a type of error that I am not sure how to address it. 

```P
Error in rule combine_contig_stats:
    jobid: 656
    output: stats/combined_contig_stats.tsv
    log: logs/assembly/combine_contig_stats.log (check log file(s) for error message)

RuleException:
CalledProcessErrorin line 952 of /home/farhad1990/miniconda3/envs/atlasenv/lib/python3.10/site-packages/atlas/workflow/rules/assemble.smk:
Command 'set -euo pipefail;  /home/farhad1990/miniconda3/envs/atlasenv/bin/python3.10 /faststorage/project/metagenomics/ccd.wp2/.snakemake/scripts/tmph6j19n1e.combine_contig_stats.py' returned non-zero exit status 1.
  File "/home/farhad1990/miniconda3/envs/atlasenv/lib/python3.10/site-packages/atlas/workflow/rules/assemble.smk", line 952, in __rule_combine_contig_stats
  File "/home/farhad1990/miniconda3/envs/atlasenv/lib/python3.10/concurrent/futures/thread.py", line 58, in run

```

and here is a shot of error log:

```P
2022-10-10 13:59:13 Uncaught exception: Traceback (most recent call last):
  File "/faststorage/project/metagenomics/ccd.wp2/.snakemake/scripts/tmph6j19n1e.combine_contig_stats.py", line 86, in <module>
    main(
  File "/faststorage/project/metagenomics/ccd.wp2/.snakemake/scripts/tmph6j19n1e.combine_contig_stats.py", line 81, in main
    parse_map_stats(sample_data, combined_stats)
  File "/faststorage/project/metagenomics/ccd.wp2/.snakemake/scripts/tmph6j19n1e.combine_contig_stats.py", line 43, in parse_map_stats
    assert df.shape[0] == 1, "Assumed only one row in file {}; found {}".format(
AssertionError: Assumed only one row in file S1/assembly/contig_stats/final_contig_stats.txt; found [0.011s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /cgroup/cpuset.    gc_std
Name: (n_scaffolds, n_contigs, scaf_bp, contig_bp, gap_pct, scaf_N50, scaf_L50, ctg_N50, ctg_L50, scaf_N90, scaf_L90, ctg_N90, ctg_L90, scaf_max, ctg_max, scaf_n_gt50K, scaf_pct_gt50K, gc_avg), dtype: object
```

What I gather, it fails to generate the final_contig_stats.txt file due to duplicate cpu set? I don't understand what does this mean and why should it only be for one of my samples, sample 1. 

Here is the final_contig_stats.txt file:

```P
[0.011s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /cgroup/cpuset.
n_scaffolds	n_contigs	scaf_bp	contig_bp	gap_pct	scaf_N50	scaf_L50	ctg_N50	ctg_L50	scaf_N90	scaf_L90	ctg_N90	ctg_L90	scaf_max	ctg_max	scaf_n_gt50K	scaf_pct_gt50K	gc_avg	gc_std
53207	55439	183334699	183197885	0.075	6494	5235	7238	4860	37280	1341	39069	1321	276801	276801	194	8.567	0.46300	0.10561
```

Does anyone know what might have caused this issue and how to troubleshoot it? It is only for one sample and appaerntly it worked for other samples. It still created the log file but with this warning in it. And the entire workflow stops with this flag that there was an error and this is the only error I see. 
Thanks very much for the help in advance. 

Kinds,
Farhad

**Comment by SilasK** [comment]
Is the `[0.011s][warning][os,container] Duplicate cpuse ...` part of the file? this is causing the error.

**Comment by farhadm1990** [comment]
Yes that is a part of it. But, how should it be generated like this? I mean, I updated atlas to atlas 2.12 and the same happened, is there any way of avoiding this for my future runs?
I actually found out that there were there other samples with the same issue. So, I deleted those files and rerun atlas all and it is fixed now and the new files seems to be okay :)

**Comment by SilasK** [comment]
I think the above comit solved it. Can you try by installing atlas from the github (see docs). best in a new conda env. 

If the error occured only in one sample I suggest you to delete the `"rm */assembly/contig_stats/*_contig_stats.txt"` and restart atlas

**Comment by farhadm1990** [comment]
Thanks Silas, 

Problem is solved now :)

**Comment by teddy256** [comment]
Hello Silas,

I tried  "rm */assembly/contig_stats/*_contig_stats.txt" as suggested but I still get the same error.
I tried installing atlas from the github but it is not working either.

Error in rule combine_contig_stats:
    jobid: 113
    input: MC2107/assembly/contig_stats/final_contig_stats.txt, R2161/assembly/contig_stats/final_contig_stats.txt, R2164/assembly/contig_stats/final_contig_stats.txt, R2166/assembly/contig_stats/final_contig_stats.txt, R2167/assembly/contig_stats/final_contig_stats.txt, R2168/assembly/contig_stats/final_contig_stats.txt, MC2107/annotation/predicted_genes/MC2107.tsv, R2161/annotation/predicted_genes/R2161.tsv, R2164/annotation/predicted_genes/R2164.tsv, R2166/annotation/predicted_genes/R2166.tsv, R2167/annotation/predicted_genes/R2167.tsv, R2168/annotation/predicted_genes/R2168.tsv, MC2107/logs/assembly/calculate_coverage/pilup_final_contigs.log, R2161/logs/assembly/calculate_coverage/pilup_final_contigs.log, R2164/logs/assembly/calculate_coverage/pilup_final_contigs.log, R2166/logs/assembly/calculate_coverage/pilup_final_contigs.log, R2167/logs/assembly/calculate_coverage/pilup_final_contigs.log, R2168/logs/assembly/calculate_coverage/pilup_final_contigs.log, MC2107/sequence_alignment/MC2107.bam, R2161/sequence_alignment/R2161.bam, R2164/sequence_alignment/R2164.bam, R2166/sequence_alignment/R2166.bam, R2167/sequence_alignment/R2167.bam, R2168/sequence_alignment/R2168.bam
    output: stats/combined_contig_stats.tsv
    log: logs/assembly/combine_contig_stats.log (check log file(s) for error message)

RuleException:
CalledProcessError in line 823 of /DATA1/home/teddy/miniconda3/envs/atlasenv/lib/python3.10/site-packages/atlas/workflow/rules/assemble.smk:
Command 'set -euo pipefail;  /DATA1/home/teddy/miniconda3/envs/atlasenv/bin/python3.10 /DATA1/home/teddy/atlas_metagenome/atlas2023/.snakemake/scripts/tmp2__1q7xe.combine_contig_stats.py' returned non-zero exit status 1.
  File "/DATA1/home/teddy/miniconda3/envs/atlasenv/lib/python3.10/site-packages/atlas/workflow/rules/assemble.smk", line 823, in __rule_combine_contig_stats
  File "/DATA1/home/teddy/miniconda3/envs/atlasenv/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

Here is the relevant log output:
2023-02-16 07:57:04 Uncaught exception: Traceback (most recent call last):
  File "/DATA1/home/teddy/miniconda3/envs/atlasenv/lib/python3.10/site-packages/atlas/workflow/rules/../scripts/utils/parsers_bbmap.py", line 207, in parse_pileup_log_file
    value = int(value_with_whitespace)
ValueError: invalid literal for int() with base 10: ' Coverage capped at 65535; please use the flag 32bit for higher values.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/DATA1/home/teddy/miniconda3/envs/atlasenv/lib/python3.10/site-packages/atlas/workflow/rules/../scripts/utils/parsers_bbmap.py", line 209, in parse_pileup_log_file
    value = float(value_with_whitespace)
ValueError: could not convert string to float: ' Coverage capped at 65535; please use the flag 32bit for higher values.'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/DATA1/home/teddy/atlas_metagenome/atlas2023/.snakemake/scripts/tmp1t3ra0c2.combine_contig_stats.py", line 86, in <module>
    main(
  File "/DATA1/home/teddy/atlas_metagenome/atlas2023/.snakemake/scripts/tmp1t3ra0c2.combine_contig_stats.py", line 81, in main
    parse_map_stats(sample_data, combined_stats)
  File "/DATA1/home/teddy/atlas_metagenome/atlas2023/.snakemake/scripts/tmp1t3ra0c2.combine_contig_stats.py", line 51, in parse_map_stats
    mapping_stats = parse_pileup_log_file(sample_data[sample]["mapping_log"])
  File "/DATA1/home/teddy/miniconda3/envs/atlasenv/lib/python3.10/site-packages/atlas/workflow/rules/../scripts/utils/parsers_bbmap.py", line 214, in parse_pileup_log_file
    raise Exception(
Exception: Error parsing line:
Note: Coverage capped at 65535; please use the flag 32bit for higher values.

 in log file R2161/logs/assembly/calculate_coverage/pilup_final_contigs.log

** Atlas version**
Recently upgraded to Atlas version: 2.13.1 Snakemake 7.18.2

**Additional context**
Assembler used: megahit because spades is incompatible with the GLIBC_2.14 on our Linux system

**Comment by SilasK** [comment]
@teddy256 https://github.com/metagenome-atlas/atlas/pull/598 should solve your problem. E.g. you would only need to reinstall atlas from GitHub. I prepare a conda release

**Comment by teddy256** [comment]
Thank you Silas,
Re-installing atlas v2.14.1 from GitHub solved the problem.
