### ISSUE TITLE
gtdbtk classify: error: one of the arguments --skip_ani_screen --mash_db is required

### ISSUE THREAD

**Issue by JustinGibbons** [metagenome-atlas/atlas#612]
Hi,

I hope you're having a good week.

I'm running atlas, version 2.14.0 Snakemake 7.18.2 on the provided test data and I get the following error:

gtdbtk classify: error: one of the arguments --skip_ani_screen --mash_db is required

I'm running on slurm, but I didn't use Snakemake to submit the job I just submitted "atlas run genomes" to sbatch.

I've attached the log file with the error and the standard output from the cluster.

Is this something you can help me with?

Thank you,

Justin G 

[classify.txt](https://github.com/metagenome-atlas/atlas/files/10768701/classify.txt)
[atlas.txt](https://github.com/metagenome-atlas/atlas/files/10768720/atlas.txt)

**Comment by SilasK** [comment]
Related to https://github.com/Ecogenomics/GTDBTk/issues/472

**Comment by SilasK** [comment]
It should be fixed with the latest commit on the master branch.

@JustinGibbons  Could you please try.

**Comment by teddy256** [comment]
Hi Silas,
I had the same error a couple days ago.

Re-running Atlas version: 2.14.1 Snakemake 7.18.2 today after your response and the same error in rule classify still occurs.  I am not sure if there is anything I have to change before re-running atlas.

**Comment by JustinGibbons** [comment]
Hi @SilasK,

I installed the latest conda environment (2.14.2) and it is now working.

Thank you for your help
